# This is a basic workflow to build and deploy an Angular app on GitHub Pages

name: Angular CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

        # Step 4: Build the Angular app
      - name: Build app bundle
        run: npm run build -- --configuration production

      - name: Rename index for routing
        run: mv dist/frontend-deploy/browser/index.html dist/frontend-deploy/browser/404.html

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          
          build_dir: dist/frontend-deploy
        env: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
